### ISSUE TITLE
Handle s3 ClientError

### ISSUE THREAD

**Issue by ps2** [WildflowerSchools/camera#2]
```
Traceback (most recent call last):
  File "./upload.py", line 52, in <module>
    upload(options.directory, options.camera_number)
  File "./upload.py", line 41, in upload
    s3.Bucket('wf-classroom-data').put_object(Key=key, Body=data)
  File "/usr/local/lib/python3.4/dist-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 599, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (BadDigest) when calling the PutObject operation (reached max retries: 4): The Content-MD5 you specified d
id not match what we received.
```

**Comment by kikiorg** [comment]
Assuming the error is a conflict with capture.py creating while upload.py is trying to upload, this fix captures to a temp file, then renames it when done, and upload.py ignores that temp file.
